### ISSUE TITLE
broken264fixer exec probléme

### ISSUE THREAD

**Issue by desreumaux** [mercmobily/broken264fixer#1]
hello,

voici mon probleme lors de l'execution de broken264fixer

1er TEST

pi@raspberrypi:~/Documents/AC88U $ sudo ./broken264fixer inputfile.264
Verifying archive integrity...  100%   MD5 checksums are OK. All good.
Uncompressing Broken 264 fixer  100%  
./main.sh: ligne 56: ../convert2 : impossible d'exécuter le fichier binaire : Erreur de format pour exec()
./main.sh: ligne 68: ../mkvmerge : impossible d'exécuter le fichier binaire : Erreur de format pour exec()
/tmp/selfgz965
mv: impossible d'évaluer 'ci-UHzEApdofk/input.mkv': Aucun fichier ou dossier de ce type
pi@raspberrypi:~/Documents/AC88U $ 

2éme TEST

pi@raspberrypi:~/Documents/AC88U $ sudo su
root@raspberrypi:/home/pi/Documents/AC88U# ./broken264fixer inputfile.264
Verifying archive integrity...  100%   MD5 checksums are OK. All good.
Uncompressing Broken 264 fixer  100%  
./main.sh: ligne 56: ../convert2 : impossible d'exécuter le fichier binaire : Erreur de format pour exec()
./main.sh: ligne 68: ../mkvmerge : impossible d'exécuter le fichier binaire : Erreur de format pour exec()
/tmp/selfgz1165
mv: impossible d'évaluer 'ci-pk8IRK3qyD/input.mkv': Aucun fichier ou dossier de ce type
root@raspberrypi:/home/pi/Documents/AC88U#

3éme TEST

root@raspberrypi:/home/pi/Documents/AC88U# cp broken264fixer /usr/bin
root@raspberrypi:/home/pi/Documents/AC88U# broken264fixer inputfile.264
Verifying archive integrity...  100%   MD5 checksums are OK. All good.
Uncompressing Broken 264 fixer  100%  
./main.sh: ligne 56: ../convert2 : impossible d'exécuter le fichier binaire : Erreur de format pour exec()
./main.sh: ligne 68: ../mkvmerge : impossible d'exécuter le fichier binaire : Erreur de format pour exec()
/tmp/selfgz1381
mv: impossible d'évaluer 'ci-3jg1gRoLGZ/input.mkv': Aucun fichier ou dossier de ce type
root@raspberrypi:/home/pi/Documents/AC88U# 

VERSION :

root@raspberrypi:/home/pi/Documents/AC88U# uname -a
Linux raspberrypi 5.4.83-v7+ #1379 SMP Mon Dec 14 13:08:57 GMT 2020 armv7l GNU/Linux

Thank you in advance for an idea
Jacques
jdesreu@aol.com

**Comment by mercmobily** [comment]
Hi,

I compiled these for X86, you seem to have an ARM processor!
I can look into compiling for arm -- you happy to give it a test?

Merc.

**Comment by desreumaux** [comment]
yes I can do the tests on my raspberrypi
regards

**Comment by mercmobily** [comment]
Hi,

Can you please run:

uname -m

And tell me what you get?

Merc.

**Comment by mercmobily** [comment]
BTW, I am trying to get an ARM version of mkvmerge

https://www.reddit.com/r/mkvtoolnix/comments/i6mp20/newer_version_of_mkvtoolnix_for_raspberry_pi_os/
https://www.reddit.com/r/mkvtoolnix/comments/l4bj31/appimage_for_arm/

**Comment by desreumaux** [comment]
hello,

uname -m       —>     armv7l   

Regards

**Comment by desreumaux** [comment]
card model : Raspberry Pi 2 Model B V1.1

**Comment by Tytouc** [comment]
I'm also eager to have it for Raspberry PI. Ok to test it.
pi4 4GB: Raspbian GNU/Linux 10 (buster)
Linux <HostName> 5.10.11-v7l+ #1399 SMP armv7l GNU/Linux

**Comment by desreumaux** [comment]
résultats de mes essais :
Fichiers .264 memorises par les caméras sur un serveur FTP dans le partage SAMSUNG sur le host 192.168.2.1
le programme de conversion s'appelle  "programme"  c'est un exécutable situé dans /bin avec tous droits d'execution
le montage sur raspbian s'appelle /MNT/SAMBA
mode d'emploi de programme :
programme fichier.264
resultats dans fichier.mp4 et dans fichier.wav



Exemple de SHELL Script appelé  "nettoyer"  qui permet la conversion de tous les fichiers .264 en .mp4 lisibles
a executer en super user a cause du mount 

cd /
echo "racine /"
mount -t cifs --verbose -o vers=1.0,user=admin,password=********** //192.168.2.1/SAMSUNG /MNT/SAMBA
echo "Montage effectué"
cd /MNT/SAMBA
echo "position sur /MNT/SAMBA"
find . -name "*.264" -exec programme "{}" \;
echo "conversions effectuées"
find . -name "*.264" -exec rm "{}" \;
echo "suppression .264 effectuée"
find . -name "*.wav" -exec rm "{}" \;




echo "suppression .wav effectuée"
cd /
echo "racine /"
umount //192.168.2.1/SAMSUNG
echo "démontage effectué"
echo "FIN du script"



Trace d'execution du SHELL Script:

root@raspberrypi:/home/pi# ./nettoyer
racine /
mount.cifs kernel mount options: ip=192.168.2.1,unc=\\192.168.2.1\SAMSUNG,vers=1.0,user=admin,pass=********
Montage effectué
position sur /MNT/SAMBA
conversions effectuées
suppression .264 effectuée
suppression .wav effectuée
racine /
démontage effectué
FIN du script
root@raspberrypi:/home/pi# ^C
root@raspberrypi:/home/pi# 


Navigation manuelle pour verification apres usage du Shell script :


root@raspberrypi:/home/pi# mount -t cifs --verbose -o vers=1.0,user=admin,password=********** //192.168.2.1/SAMSUNG /MNT/SAMBA
mount.cifs kernel mount options: ip=192.168.2.1,unc=\\192.168.2.1\SAMSUNG,vers=1.0,user=admin,pass=********
root@raspberrypi:/home/pi# cd /MNT/SAMBA
root@raspberrypi:/MNT/SAMBA# ls
Cam0   Cam2   Cam4
Cam1   Cam3  
root@raspberrypi:/MNT/SAMBA# cd Cam0
root@raspberrypi:/MNT/SAMBA/Cam0# ls
20210211  20210212
root@raspberrypi:/MNT/SAMBA/Cam0# cd 20210212
root@raspberrypi:/MNT/SAMBA/Cam0/20210212# ls
images	record
root@raspberrypi:/MNT/SAMBA/Cam0/20210212# cd record
root@raspberrypi:/MNT/SAMBA/Cam0/20210212/record# ls -l
total 57344
-rwxrwxrwx 1 root root 2047858 févr. 12 09:08 A210212_062250_062305.mp4
-rwxrwxrwx 1 root root 2193485 févr. 12 09:08 A210212_070135_070149.mp4
-rwxrwxrwx 1 root root 2596228 févr. 12 11:54 A210212_100407_100422.mp4
-rwxrwxrwx 1 root root 2803414 févr. 12 11:54 A210212_100757_100812.mp4
-rwxrwxrwx 1 root root 2664698 févr. 12 11:54 A210212_102725_102740.mp4
-rwxrwxrwx 1 root root 2556733 févr. 12 11:54 A210212_102901_102915.mp4
-rwxrwxrwx 1 root root 2249371 févr. 12 11:54 A210212_102947_103001.mp4
-rwxrwxrwx 1 root root 2554047 févr. 12 11:54 A210212_104434_104448.mp4
-rwxrwxrwx 1 root root 2129740 févr. 12 11:54 A210212_104449_104503.mp4
-rwxrwxrwx 1 root root 2319817 févr. 12 11:54 A210212_110959_111013.mp4
-rwxrwxrwx 1 root root 2294152 févr. 12 11:54 A210212_111022_111037.mp4
-rwxrwxrwx 1 root root 2381647 févr. 12 11:54 A210212_111712_111726.mp4
-rwxrwxrwx 1 root root 2453926 févr. 12 11:54 A210212_111727_111742.mp4
-rwxrwxrwx 1 root root 2212667 févr. 12 16:20 A210212_134715_134730.mp4
-rwxrwxrwx 1 root root 2272451 févr. 12 16:20 A210212_134754_134809.mp4
-rwxrwxrwx 1 root root 2318146 févr. 12 16:20 A210212_143719_143734.mp4
-rwxrwxrwx 1 root root 2524201 févr. 12 16:20 A210212_151225_151240.mp4
root@raspberrypi:/MNT/SAMBA/Cam0/20210212/record# cd ..
root@raspberrypi:/MNT/SAMBA/Cam0/20210212# cd ..
root@raspberrypi:/MNT/SAMBA/Cam0# cd ..
root@raspberrypi:/MNT/SAMBA# cd ..
root@raspberrypi:/MNT# umount //192.168.2.1/SAMSUNG
root@raspberrypi:/MNT# 

QUESTION : comment mettre a disposition le SHELL Script et l'executable Raspian car ce site ne veux pas les prendre en charge ?

cordialement

**Comment by mercmobily** [comment]
Hang on a sec, I don't speak French, and I am a little confused!

**Comment by desreumaux** [comment]
hello,

used source program called source.c :

/*
 * convert weird *.264 file to mp4 and wav
 * -raspo666 2018
 */question

#include <stdio.h>
#include <stdlib.h>
#include <strings.h>
#include <string.h>


#ifndef bzero
#define bzero(b,len) (memset((b), '\0', (len)), (void) 0)
#endif // bzero
#ifndef bcopy
#define bcopy(b1,b2,len) (memmove((b2), (b1), (len)), (void) 0)
#endif // bcopy

/*WAV*/


typedef struct wav_header
{question
    // RIFF Header
    char riff_header[4]; // Contains "RIFF"
    int wav_size; // Size of the wav portion of the file, which follows the first 8 bytes. File size - 8
    char wave_header[4]; // Contains "WAVE"

    // Format Header
    char fmt_header[4]; // Contains "fmt " (includes trailing space)
    int fmt_chunk_size; // Should be 16 for PCM
    short audio_format; // Should be 1 for PCM. 3 for IEEE Float
    short num_channels;
    int sample_rate;
    int byte_rate; // Number of bytes per second. sample_rate * num_channels * Bytes Per Sample
    short sample_alignment; // num_channels * Bytes Per Sample
    short bit_depth; // Number of bits per sample

    // Data
    char data_header[4]; // Contains "data"
    int data_bytes; // Number of bytes in data. Number of samples * num_channels * sample byte size
    // uint8_t bytes[]; // Remainder of wave file is bytes
} wav_header;


int main(int ac, char **av)
{
    FILE *in,*out,*outa;
    wav_header ahead;

    char *buffer,*p,ccode[5],*strbuf,*strp;
    int count,bufsiz,abytes;
    int len = 0;question

    if(ac != 2)
        exit(printf("use %s <file> \n",av[0]));

    if(!(in = fopen(av[1],"rb")))
        exit(printf("cannot open %s for reading.\n",av[1]));

    /* try to allocate a buffer size of infile */
    fseek(in,0,SEEK_END);
    bufsiz = ftell(in);
    rewind(in);
    if(!(buffer = malloc(bufsiz)))
        exit(printf("unable to allocate %d bytes\n",bufsiz));
    p = buffer;
    /* open output */


    if(!(strbuf = malloc(strlen(av[1])+5)))
        exit(printf("no mem for strings\n"));


    strp = strstr(av[1],".264");
    if(strp != NULL)
        *strp = '\0';
    strp = av[1];


    sprintf(strbuf,"%s.mp4",strp);

    if(!(out = fopen(strbuf,"wb")))
        exit(printf("cannot open %s for writing.\n",av[2]));

    sprintf(strbuf,"%s.wav",strp);

    if(!(outa = fopen(strbuf,"wb")))
        exit(printf("cannot open %s for writing.\n",strbuf));

    fwrite(&ahead,sizeof(wav_header),1,outa);
    /* get data */
    count = fread(buffer,1,bufsiz,in);
    abytes = 0;
    if(count != bufsiz)
    {
        printf("could only read %d of %d bytes\n",count,bufsiz);
        exit(0);
    }
    /* Throw first 0x10 bytes of garbage/fileheader plus first videoheader */
    p += 0x10;

    while(p-buffer < bufsiz)
    {
        bzero(ccode,5);
        bcopy(p,ccode,4);
        p += 4;
        bcopy(p,&len,4);
        if(!(strncmp((char *)ccode,"HXAF",4)))
        {
            p += 0xc;
            p += 4; // {0x0001, 0x5000} whatever that means, it must go, it's no audio
            len -= 4;
            printf("code: HXAF audio  %d bytes\n",len);
            fwrite(p,1,len,outa);
            p += len;
            abytes += len;
            continue;
        }
        else if(!(strncmp((char *)ccode,"HXFI",4)))
        {
            printf("found code HXFI, exit\n");
            break; /* some sort of table follows */
        }
        /* this will break if there's some other ccode ! */
        printf("code: %s video %d bytes\n",ccode,len);
        p += 0xc;
        fwrite(p,1,len,out);
        p += len;
    }

    /* wav header */

    strncpy(ahead.riff_header,"RIFF",4);
    strncpy(ahead.wave_header,"WAVE",4);
    strncpy(ahead.fmt_header,"fmt ",4);
    strncpy(ahead.data_header,"data",4);

    ahead.fmt_chunk_size = 16;
    ahead.audio_format = 0x6;
    ahead.num_channels = 1;
    ahead.sample_rate = 8000;
    ahead.byte_rate = 8000; // 16 ??
    ahead.sample_alignment = 2;
    ahead.bit_depth = 16;
    ahead.data_bytes = abytes;
    ahead.wav_size = abytes + sizeof(wav_header) - 8;
    fseek(outa,0,SEEK_SET);
    fwrite(&ahead,sizeof(wav_header),1,outa);

    free(buffer);
    fclose(in);
    fclose(out);
    fclose(outa);
    exit(0);

}

compiled by :

gcc source.c -o programme
chmod 777 programme
cp programme /bin


results of my tests:
.264 files stored by the cameras on an FTP server in the SAMSUNG share on the host 192.168.2.1
the conversion program is called "programme" it is an executable located in /bin with full execution rights
the mount on raspbian is called /MNT/SAMBA


program instructions :

programme fichier.264 
results in file .mp4 and in file .wav



Example of SHELL Script called "nettoyer" which converts all .264 files into playable .mp4 files
to run as super user because of the mount
I don't need the .wav files because I don't use the sound and the time stamp is directly in the video of my cameras


content of the "nettoyer" script

cd /
echo "racine /"
mount -t cifs --verbose -o vers = 1.0, utilisateur = admin, mot de passe = ********** //192.168.2.1/SAMSUNG / MNT / SAMBA
echo "Montage effectué "
cd / MNT / SAMBA
echo" position sur / MNT / SAMBA "
find. -name " 0,264" programme exec "{}";
echo "conversions effectuées"
find. -name " 0,264" rm exec "{}";
echo "suppression .264 effectuée"
find. -nom "* .wav" -exec rm "{}";
echo "suppression .wav effectuée"
cd /
echo "racine /"
umount //192.168.2.1/SAMSUNG
echo "démontage effectué"
echo "FIN du script"


SHELL Script execution trace :

root @ raspberrypi: / home / pi # ./nettoyer
racine /
mount.cifs options de montage du noyau: ip = 192.168.2.1, unc = \ 192.168.2.1 \ SAMSUNG, vers = 1.0, user = admin, pass = **** ****
Montage effectué
position sur / MNT / SAMBA
conversions effectuées
suppression .264 effectué
suppression .wav effectué
racine /
démontage effectué
FIN du script
root @ raspberrypi: / home / pi # ^ C
root @ raspberrypi: / home / pi #


Manual navigation for verification after using the Shell script:

root @ raspberrypi: / home / pi # mount -t cifs --verbose -o vers = 1.0, user = admin, password = ********** //192.168.2.1/SAMSUNG / MNT / SAMBA
mount Options de montage du noyau .cifs: ip = 192.168.2.1, unc = \ 192.168.2.1 \ SAMSUNG, vers = 1.0, user = admin, pass = ********
root @ raspberrypi: / home / pi # cd / MNT / SAMBA
root @ raspberrypi: / MNT / SAMBA # ls
Cam0 Cam2 Cam4
Cam1 Cam3
root @ raspberrypi: / MNT / SAMBA # cd Cam0
root @ raspberrypi: / MNT / SAMBA / Cam0 # ls
20210211 20210212
root @ raspberrypi: / MNT / SAMBA / Cam0 # cd 20210212
root @ raspberrypi: / MNT / SAMBA / Cam0 / 20210212 # ls
images record
root @ raspberrypi: / MNT / SAMBA / Cam0 / 20210212 # cd record
root @ raspberrypi: / MNT / SAMBA / Cam0 / 20210212 / enregistrement # ls -l
total 57344
-rwxrwxrwx 1 racine racine 2047858 févr. 12 09:08 A210212_062250_062305.mp4
-rwxrwxrwx 1 racine racine 2193485 févr. 12 09:08 A210212_070135_070149.mp4
-rwxrwxrwx 1 racine racine 2596228 févr. 12 11:54 A210212_100407_100422.mp4
-rwxrwxrwx 1 racine racine 2803414 févr. 12 11:54 A210212_100757_100812.mp4
-rwxrwxrwx 1 racine racine 2664698 févr. 12 11:54 A210212_102725_102740.mp4
-rwxrwxrwx 1 racine racine 2556733 févr. 12 11:54 A210212_102901_102915.mp4
-rwxrwxrwx 1 racine racine 2249371 févr. 12 11:54 A210212_102947_103001.mp4
-rwxrwxrwx 1 racine racine 2554047 févr. 12 11:54 A210212_104434_104448.mp4
-rwxrwxrwx 1 racine racine 2129740 févr. 12 11:54 A210212_104449_104503.mp4
-rwxrwxrwx 1 racine racine 2319817 févr. 12 11:54 A210212_110959_111013.mp4
-rwxrwxrwx 1 racine racine 2294152 févr. 12 11:54 A210212_111022_111037.mp4
-rwxrwxrwx 1 racine racine 2381647 févr. 12 11:54 A210212_111712_111726.mp4
-rwxrwxrwx 1 racine racine 2453926 févr. 12 11:54 A210212_111727_111742.mp4
-rwxrwxrwx 1 racine racine 2212667 févr. 12 16:20 A210212_134715_134730.mp4
-rwxrwxrwx 1 racine racine 2272451 févr. 12 16:20 A210212_134754_134809.mp4
-rwxrwxrwx 1 racine racine 2318146 févr. 12 16:20 A210212_143719_143734.mp4
-rwxrwxrwx 1 racine racine 2524201 févr. 12 16:20 A210212_151225_151240.mp4
root @ raspberrypi: / MNT / SAMBA / Cam0 / 20210212 / record # cd ..
root @ raspberrypi: / MNT / SAMBA / Cam0 / 20210212 # cd ..
root @ raspberrypi: / MNT / SAMBA / Cam0 # cd ..
root @ raspberrypi: / MNT / SAMBA # cd ..
root @ raspberrypi: / MNT # umount //192.168.2.1/SAMSUNG
root @ raspberrypi: / MNT #

files converted to .mp4 can be read by different players such as "GOM Player" for example

QUESTION: how to make the SHELL Script and the Raspian executable available because we cannot deposit executables ?

regards.

**Comment by desreumaux** [comment]
hello,
Please note it is possible that my editor or the pasted copy added spaces near / or \ but you can easily correct if necessary
regards.
Jack

**Comment by desreumaux** [comment]
Hello,
1) My editor or the pasted copy change some    *.264    by   “ 0,264”  In the nettoyer script but you can easily correct it
2) After cleaning by using “programme” Gom Player and Infuse read the .mp4 videos correctly but vlc refuses to read.
Regards
Jack

**Comment by mercmobily** [comment]
I am sorry, at this stage I am focussing on finding a way to get a
statically compiled mkvmerge executable targeting ARM (and therefore
running on the Pi)
I am trying

**Comment by mercmobily** [comment]
Closed?

**Comment by desreumaux** [comment]
after compilation of the source the conversion program which I called "program" works normally
I integrated it into a shell script to automate the conversion of several hundred videos stored on a cifs server (samba)
here is the corresponding shell
the problem is therefore solved for my needs.
![D31F33D0-F9E2-4991-BD9E-53FEE3AC8F2A](https://user-images.githubusercontent.com/77922349/115769923-65a5d000-a3ac-11eb-8fd3-e9d755e5289d.jpeg)

**Comment by desreumaux** [comment]
thank you for everything
regards
Jacques
