### ISSUE TITLE
Compile on Linux ARM

### ISSUE THREAD

**Issue by etisalive** [mercmobily/broken264fixer#3]
Hi how can i compile it for Linux ARM?

**Comment by mercmobily** [comment]
I don't see why not. Are you having trouble with it?

**Comment by mercmobily** [comment]
Have you tried just running the file through the compiler? What are you getting?

**Comment by mercmobily** [comment]
If you don't know how to compile, can you just try:

````
cc -o convert2 convert2.c
````

And then run the command to make the bundle:

````
./createLinuxBundle.sh
````

?

**Comment by etisalive** [comment]
Thank you for the answer. I get the following error when trying to convert the video file:
`
Verifying archive integrity...  100%   MD5 checksums are OK. All good.
Uncompressing Broken 264 fixer  100%  
Duration 1080
HXFI End if File
./main.sh: line 66: ../mkvmerge: cannot execute binary file: Exec format error
/tmp/selfgz3346426
mv: cannot stat 'ci-dDGhPZHPN5/input.mkv': No such file or directory
`
I compile it on Raspberry Pi

**Comment by etisalive** [comment]
Ok I was able to solve the problem - I had to use the local "mkvmerge". But I noticed that you can not enter the video file with the folder path.

**Comment by mercmobily** [comment]
Wait -- is it working now for you...?

**Comment by etisalive** [comment]
Yes it working now on my Raspberry Pi.

**Comment by mercmobily** [comment]
Hi,

Ah of course you couldn't run the precompiled mkvmerge! Silly me!
AI wonder if I should provide the same package for ARM...?

**Comment by etisalive** [comment]
Sure why not?!

**Comment by mercmobily** [comment]
OK. Will consider. I am glad it worked for you! :D
